//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photovoltic_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_WeatherEntities : DbContext
    {
        public DB_WeatherEntities()
            : base("name=DB_WeatherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tbl_Projects> tbl_Projects { get; set; }
        public virtual DbSet<tbl_Products> tbl_Products { get; set; }
        public virtual DbSet<tbl_HistoryWeather> tbl_HistoryWeather { get; set; }
        public virtual DbSet<tbl_WeatherData> tbl_WeatherData { get; set; }
        public virtual DbSet<tbl_ProductAssignment> tbl_ProductAssignment { get; set; }
    
        public virtual ObjectResult<GetWeatherByCoordinates_Result> GetWeatherByCoordinates(Nullable<double> latitude, Nullable<double> longitude)
        {
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWeatherByCoordinates_Result>("GetWeatherByCoordinates", latitudeParameter, longitudeParameter);
        }
    }
}
