//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photovoltic_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WeatherData
    {
        public int ID { get; set; }
        public Nullable<int> ProductAssignmentID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> LocalObservationDateTime { get; set; }
        public string EpochTime { get; set; }
        public string WeatherText { get; set; }
        public Nullable<int> WeatherIcon { get; set; }
        public Nullable<bool> HasPrecipitation { get; set; }
        public string PrecipitationType { get; set; }
        public Nullable<bool> IsDayTime { get; set; }
        public Nullable<double> TemperatureMetricValue { get; set; }
        public string TemperatureMetricUnit { get; set; }
        public Nullable<int> TemperatureMetricUnitType { get; set; }
        public Nullable<int> TemperatureImperialValue { get; set; }
        public string TemperatureImperialUnit { get; set; }
        public Nullable<int> TemperatureImperialUnitType { get; set; }
        public string MobileLink { get; set; }
        public string Link { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
