//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photovoltic_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Projects
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Location { get; set; }
        public Nullable<double> CapacityMW { get; set; }
        public Nullable<int> PanelsCount { get; set; }
        public string InverterModel { get; set; }
        public Nullable<int> InverterCount { get; set; }
        public Nullable<bool> TrackingSystem { get; set; }
        public string OwnerName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string InstallationCompany { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
