//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photovoltic_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HistoryWeather
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Sunrise { get; set; }
        public Nullable<System.DateTime> Sunset { get; set; }
        public Nullable<double> SolarIrradiance_Value { get; set; }
        public string SolarIrradiance_Unit { get; set; }
        public string SolarIrradiance_UnitType { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
